#!/usr/bin/env bash

set -e

ENVIRONMENT=$1
PROJECT_DIR=$(git rev-parse --show-toplevel)

case $ENVIRONMENT in
  test | dev | stg | prod)
    source $PROJECT_DIR/env/$ENVIRONMENT
    ;;
  *)
    echo "Unrecognized environment '${ENVIRONMENT}'"
    exit 1
    ;;
esac

flyway \
  -driver=com.mysql.cj.jdbc.Driver \
  -url=jdbc:mysql://$DB_HOST:$DB_PORT/$DB_NAME \
  -user=$DB_USER \
  -password=$DB_PASS \
  -locations=filesystem:$PROJECT_DIR/migrations \
  migrate
